teams:
  oci-proxy-admins:
    description: Admin access to kubernetes-sigs/oci-proxy
    maintainers:
    - spiffxp
    members:
    - ameukam
    - dims
    - thockin
    privacy: closed
  oci-proxy-maintainers:
    description: Write access to kubernetes-sigs/oci-proxy
    maintainers:
    - spiffxp
    - bobyMCbobs
    - riaankl
    - hh
    members:
    - ameukam
    - dims
    - thockin
    privacy: closed
